### ISSUE TITLE
Consider handling multiple VRS versions in a single version

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrsatile-pydantic#47]
This package is used all throughout our applications and has caused us to pin versions. It might be nice to somehow handle multiple VRS versions in one release. Not sure if this is the best approach, but will think on it.

**Comment by jsstevenson** [comment]
My first thought is that this seems like a good bit of manual (error-prone?) work to maintain. Some kind of auto-generated solution would be nice.

**Comment by korikuzma** [comment]
Ya, I wanted to do a similar approach as vrs-python with the VRS submodules

**Comment by korikuzma** [comment]
I’m also wondering if we should separate this out into 2 different packages - one for VRS and one for VRSATILE. VRSATILE isn’t versioned at the moment, but I imagine it eventually will be.

**Comment by korikuzma** [comment]
Maybe look into this again: https://github.com/koxudaxi/datamodel-code-generator/

**Comment by korikuzma** [comment]
VRS-Python is now handling VRS models in 2-alpha+
